; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = release

[common]

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = yb_esp32s3_dac
monitor_port = COM[3456789]
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time, colorize
upload_port = COM[3456789]
upload_speed = 921600
; --- for boards with only 4MB Flash ---
;board_build.partitions = default.csv
;board_upload.flash_size = 4MB
;board_upload.maximum_size = 4194304
; --- for boards with 16MB Flash ---
;board_build.partitions = default_16MB.csv
;board_upload.flash_size = 16MB
;board_upload.maximum_size = 16777216
; ---
lib_deps = 
  Adafruit BusIO
  Adafruit TLV320 I2S
  TLV320DAC3101
build_flags = 
extra_scripts = add_tasks.py

[env:release]
build_flags = 
	${env.build_flags}
; 0 no debug output, 1 errors, 2 warnings, 3 infos, 4 debug info, 5 verbose  
	-DCORE_DEBUG_LEVEL=2
  ;-Wall
  ;-Wextra
  -Wunreachable-code
  ;-Wformat=2
  ;-Werror=unused-variable
  -Werror=unused-but-set-variable
build_unflags = 
  ${env.build_unflags}
lib_deps = 
	${env.lib_deps}

[env:debug]
monitor_filters = 
  ${env.monitor_filters}
;  debug
build_type = debug
debug_init_break = tbreak setup
;debug_init_break = break loop
;
;debug_tool = custom
debug_tool = esp-builtin  ; ESP32-S3
debug_server = ${platformio.packages_dir}/tool-openocd-esp32/bin/openocd 
  -fboard/esp32s3-builtin.cfg
debug_port = localhost:3333
build_flags = 
  ${env.build_flags}
; 0 no debug output, 1 errors, 2 warnings, 3 infos, 4 debug info, 5 verbose,   
	-DCORE_DEBUG_LEVEL=4
  -D_DEBUG_
lib_deps = 
  ${env.lib_deps}

